var hierarchy =
[
    [ "Exception", null, [
      [ "PiPiCSharp.Exceptions.PiPiCSharpAppearanceException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_appearance_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpEditFieldException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_edit_field_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpExtractException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_extract_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpFieldCompatibilityException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_field_compatibility_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpFillFieldException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_fill_field_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpFontManageException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_font_manage_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpManageFieldException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_manage_field_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpMultiOperateException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_multi_operate_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpOperateException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_operate_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpPageException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_page_exception.html", null ],
      [ "PiPiCSharp.Exceptions.PiPiCSharpUnknownException", "class_pi_pi_c_sharp_1_1_exceptions_1_1_pi_pi_c_sharp_unknown_exception.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "PiPiCSharp.Adapters.PiPiCSharpEditAdapter", "class_pi_pi_c_sharp_1_1_adapters_1_1_pi_pi_c_sharp_edit_adapter.html", null ],
      [ "PiPiCSharp.Adapters.PiPiCSharpExtractAdapter", "class_pi_pi_c_sharp_1_1_adapters_1_1_pi_pi_c_sharp_extract_adapter.html", null ],
      [ "PiPiCSharp.Adapters.PiPiCSharpFillAdapter", "class_pi_pi_c_sharp_1_1_adapters_1_1_pi_pi_c_sharp_fill_adapter.html", null ],
      [ "PiPiCSharp.Adapters.PiPiCSharpFontManageAdapter", "class_pi_pi_c_sharp_1_1_adapters_1_1_pi_pi_c_sharp_font_manage_adapter.html", null ],
      [ "PiPiCSharp.Adapters.PiPiCSharpMultiOperateAdapter", "class_pi_pi_c_sharp_1_1_adapters_1_1_pi_pi_c_sharp_multi_operate_adapter.html", null ],
      [ "PiPiCSharp.Adapters.PiPiCSharpOperateAdapter", "class_pi_pi_c_sharp_1_1_adapters_1_1_pi_pi_c_sharp_operate_adapter.html", null ],
      [ "PiPiCSharp.Adapters.PiPiCSharpPageAdapter", "class_pi_pi_c_sharp_1_1_adapters_1_1_pi_pi_c_sharp_page_adapter.html", null ],
      [ "PiPiCSharp.PiPiCSharpEditor", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_editor.html", null ],
      [ "PiPiCSharp.PiPiCSharpExtractor", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_extractor.html", null ],
      [ "PiPiCSharp.PiPiCSharpFiller", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_filler.html", null ],
      [ "PiPiCSharp.PiPiCSharpFontManager", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_font_manager.html", null ],
      [ "PiPiCSharp.PiPiCSharpMultiOperator", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_multi_operator.html", null ],
      [ "PiPiCSharp.PiPiCSharpOperator", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_operator.html", null ],
      [ "PiPiCSharp.PiPiCSharpPager", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_pager.html", null ]
    ] ],
    [ "PiPiCSharp.PiPiCSharpConstants", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_constants.html", null ],
    [ "PiPiCSharp.Utils.PiPiCSharpDelegateInvoker", "class_pi_pi_c_sharp_1_1_utils_1_1_pi_pi_c_sharp_delegate_invoker.html", null ],
    [ "PiPiCSharp.Utils.PiPiCSharpDelegateTransformer", "class_pi_pi_c_sharp_1_1_utils_1_1_pi_pi_c_sharp_delegate_transformer.html", null ],
    [ "PiPiCSharp.Invokers.PiPiCSharpEditInvoker", "class_pi_pi_c_sharp_1_1_invokers_1_1_pi_pi_c_sharp_edit_invoker.html", null ],
    [ "PiPiCSharp.Utils.PiPiCSharpExceptionDispatcher", "class_pi_pi_c_sharp_1_1_utils_1_1_pi_pi_c_sharp_exception_dispatcher.html", null ],
    [ "PiPiCSharp.Invokers.PiPiCSharpExtractInvoker", "class_pi_pi_c_sharp_1_1_invokers_1_1_pi_pi_c_sharp_extract_invoker.html", null ],
    [ "PiPiCSharp.PiPiCSharpField", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_field.html", null ],
    [ "PiPiCSharp.Invokers.PiPiCSharpFillInvoker", "class_pi_pi_c_sharp_1_1_invokers_1_1_pi_pi_c_sharp_fill_invoker.html", null ],
    [ "PiPiCSharp.Invokers.PiPiCSharpFontManageInvoker", "class_pi_pi_c_sharp_1_1_invokers_1_1_pi_pi_c_sharp_font_manage_invoker.html", null ],
    [ "PiPiCSharp.Invokers.PiPiCSharpMultiOperateInvoker", "class_pi_pi_c_sharp_1_1_invokers_1_1_pi_pi_c_sharp_multi_operate_invoker.html", null ],
    [ "PiPiCSharp.Invokers.PiPiCSharpOperateInvoker", "class_pi_pi_c_sharp_1_1_invokers_1_1_pi_pi_c_sharp_operate_invoker.html", null ],
    [ "PiPiCSharp.PiPiCSharpPage", "class_pi_pi_c_sharp_1_1_pi_pi_c_sharp_page.html", null ],
    [ "PiPiCSharp.Invokers.PiPiCSharpPageInvoker", "class_pi_pi_c_sharp_1_1_invokers_1_1_pi_pi_c_sharp_page_invoker.html", null ],
    [ "PiPiCSharp.Natives.PiPiEditWrapper", "class_pi_pi_c_sharp_1_1_natives_1_1_pi_pi_edit_wrapper.html", null ],
    [ "PiPiCSharp.Natives.PiPiExtractWrapper", "class_pi_pi_c_sharp_1_1_natives_1_1_pi_pi_extract_wrapper.html", null ],
    [ "PiPiCSharp.Natives.PiPiFillWrapper", "class_pi_pi_c_sharp_1_1_natives_1_1_pi_pi_fill_wrapper.html", null ],
    [ "PiPiCSharp.Natives.PiPiFontManageWrapper", "class_pi_pi_c_sharp_1_1_natives_1_1_pi_pi_font_manage_wrapper.html", null ],
    [ "PiPiCSharp.Natives.PiPiMultiOperateWrapper", "class_pi_pi_c_sharp_1_1_natives_1_1_pi_pi_multi_operate_wrapper.html", null ],
    [ "PiPiCSharp.Natives.PiPiOperateWrapper", "class_pi_pi_c_sharp_1_1_natives_1_1_pi_pi_operate_wrapper.html", null ],
    [ "PiPiCSharp.Natives.PiPiPageWrapper", "class_pi_pi_c_sharp_1_1_natives_1_1_pi_pi_page_wrapper.html", null ]
];